MAX_LENGTH: 30 
EMBEDDING_DIM: 768
BIG_EMBEDDING_FILE: "embeddings.dat"
SAMPLE_EMBEDDING_FILE: "sample_embeddings.pkl"
SAMPLE_PCA_FILE: "sample_pca.pkl" 
SAMPLE_KMEANS_FILE: "sample_kmeans.pkl"
N_CLUSTERS: 30
ANTI_FILE: "dataverse_files/TweetDataset_AntiBrexit_Jan-Mar2022.csv"
PRO_FILE: "dataverse_files/TweetDataset_ProBrexit_Jan-Mar2022.csv"

